# Generated by Django 4.2.6 on 2023-10-31 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    'aluno',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='escola.aluno',
                    ),
                ),
                (
                    'curso',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='escola.curso',
                    ),
                ),
            ],
            options={
                'unique_together': {('aluno', 'curso')},
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
