# Generated by Django 4.2.6 on 2023-10-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_notas_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='descricao_curso',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notas',
            name='nome_aluno',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
